package com.summary.zkhdsummary.bean;

import java.util.Date;

public class log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.date
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.hot
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private Integer hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.state
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.userid
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private String log;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.date
     *
     * @return the value of log.date
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.date
     *
     * @param date the value for log.date
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.hot
     *
     * @return the value of log.hot
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.hot
     *
     * @param hot the value for log.hot
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.state
     *
     * @return the value of log.state
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.state
     *
     * @param state the value for log.state
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.userid
     *
     * @return the value of log.userid
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.userid
     *
     * @param userid the value for log.userid
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log
     *
     * @return the value of log.log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log
     *
     * @param log the value for log.log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setLog(String log) {
        this.log = log == null ? null : log.trim();
    }
}