package com.summary.zkhdsummary.bean;

public class power {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.id
     *
     * @mbggenerated Mon Jul 30 16:53:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.power
     *
     * @mbggenerated Mon Jul 30 16:53:55 CST 2018
     */
    private String power;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.id
     *
     * @return the value of power.id
     *
     * @mbggenerated Mon Jul 30 16:53:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.id
     *
     * @param id the value for power.id
     *
     * @mbggenerated Mon Jul 30 16:53:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.power
     *
     * @return the value of power.power
     *
     * @mbggenerated Mon Jul 30 16:53:55 CST 2018
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.power
     *
     * @param power the value for power.power
     *
     * @mbggenerated Mon Jul 30 16:53:55 CST 2018
     */
    public void setPower(String power) {
        this.power = power == null ? null : power.trim();
    }
}