package com.summary.zkhdsummary.bean;

public class user {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private Integer card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    private Integer userPower;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card
     *
     * @return the value of user.card
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public Integer getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card
     *
     * @param card the value for user.card
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setCard(Integer card) {
        this.card = card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_power
     *
     * @return the value of user.user_power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public Integer getUserPower() {
        return userPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_power
     *
     * @param userPower the value for user.user_power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    public void setUserPower(Integer userPower) {
        this.userPower = userPower;
    }
}