server:
  port: 8083

spring:
    datasource:
        name: summary
        url: jdbc:mysql://192.168.103.7:3306/summary?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: admin123

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapping/*.xml