server:
  port: 8083

spring:
    datasource:
        name: summary
        url: jdbc:mysql://127.0.0.1:3306/summary
        username: root
        password: admin123

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapping/*.xml  #映射文件路径
    type-aliases-package: com.summary.zkhdsummary.bean  #实体类路径
