package com.summary.zkhdsummary.mapper;

import com.summary.zkhdsummary.bean.log;
import com.summary.zkhdsummary.bean.logExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface logMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int countByExample(logExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int deleteByExample(logExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int insert(log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int insertSelective(log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    List<log> selectByExampleWithBLOBs(logExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    List<log> selectByExample(logExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    log selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") log record, @Param("example") logExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") log record, @Param("example") logExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int updateByExample(@Param("record") log record, @Param("example") logExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int updateByPrimaryKeySelective(log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int updateByPrimaryKey(log record);
}