package com.summary.zkhdsummary.mapper;

import com.summary.zkhdsummary.bean.power;
import com.summary.zkhdsummary.bean.powerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface powerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int countByExample(powerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int deleteByExample(powerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int insert(power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int insertSelective(power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    List<power> selectByExample(powerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    power selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") power record, @Param("example") powerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int updateByExample(@Param("record") power record, @Param("example") powerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int updateByPrimaryKeySelective(power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated Mon Jul 30 17:41:31 CST 2018
     */
    int updateByPrimaryKey(power record);
}